title: 월출봉은 불암산
url: "https://reddiana.github.io/"
baseurl: "/tech"

# defaults:
#   -
#     scope:
#       path: "/tech/" # empty string for all files
#     values:
#       title: 어화둥둥

description: 어화둥둥
author:
  name: 바쏠로뮤
  email: reddiana@gmail.com
  github: reddiana
  twitter:
  pinterest:
  linkedin:
  bio: 월출봉에 달 뜨거든 날 불러주오
  email_md5: 

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: reddiana
google_analytics:
  id:

sidebar_background_image: https://i.imgur.com/RSG6X2o.jpg

permalink: /:title:output_ext

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

analytics.js: #ga('send', 'pageview', '/search_results.php?q=keyword');

BASE_PATH:

plugins:
  - jekyll-paginate

# include:
#  - _site

# theme: jekyll-theme-slate
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
