theme: jekyll-theme-dinky
title: "어화둥둥"
description: "월출봉에 달 뜨거든 날 불러주오"

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

author:
  name             : "서세일"
  facebook         : "reddiana@gmail.com"
  github           : "reddiana"

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed  